# Dockerfile > Docker Image > Run Docker Containers

FROM alpine:latest

CMD [ "echo", "hello from packages" ]

LABEL org.opencontainers.image.source=https://github.com/davaadorj-test-orga/8-ueb-publish-package
LABEL org.opencontainers.image.description="My image description"
LABEL org.opencontainers.image.licenses=MIT
