name: publish npm package

on:
  push:
    paths:
      - "sample-packages/npm/package.json"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'sample-packages/npm'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install

  publish-my-npm-pkg:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'sample-packages/npm'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}
